# This file was generated by GoReleaser. DO NOT EDIT.
class Rename < Formula
  desc "Unix Rename command, written in Go"
  homepage "https://github.com/fberge/rename"
  url "https://github.com/fbergen/rename/releases/download/v0.1.3/rename_0.1.3_Darwin_x86_64.tar.gz"
  version "0.1.3"
  sha256 "ac060766cc4161c7bbcefb33adc7be21b74efdafad0e3a53667461855769ac8c"

  def install
    bin.install "rename"
  end
end
